### ISSUE TITLE
Performance on instant-ngp

### ISSUE THREAD

**Issue by wen-yuan-zhang** [veliglmz/tiny-cuda-nn-python#2]
Thanks for your excellent work! I am well aware that this job is not easy. I wonder that have you tested the performance of this implementation in instant-ngp? For example, how about the PSNR differences between instant-ngp and your python implementation?

**Comment by veliglmz** [comment]
Thank you for your comments.  I compared it with the tiny-cuda-nn repo. I only implemented multiresolution hash encoding paper last year. When comparing our implementation with the original repo, they achieved higher PSNR scores between (+0.5, +1.0) with faster convergence. However, two months ago I compared it again to add the final results to my graduate thesis, I got significantly higher PSNR scores without any changes in our code. I will share my graduate thesis in a month. You can find the comparison there. If you have detailed questions, you can email me.

**Comment by wen-yuan-zhang** [comment]
Many thanks! Looking forward to your project!

**Comment by veliglmz** [comment]
Hi. I shared my thesis [here](https://github.com/veliglmz/grid-based-super-resolution-using-spatial-hash-encoding). Have a nice day.

**Comment by wen-yuan-zhang** [comment]
Thanks for your generous sharing! It will definitely be of great help to me.
